# Generated by Django 5.0.2 on 2025-05-20 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pratica',
            name='data_modifica',
        ),
        migrations.RemoveField(
            model_name='pratica',
            name='descrizione',
        ),
        migrations.RemoveField(
            model_name='pratica',
            name='identificativo',
        ),
        migrations.RemoveField(
            model_name='pratica',
            name='proprietario',
        ),
        migrations.AddField(
            model_name='pratica',
            name='data_creazione',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pratica',
            name='nome_pratica',
            field=models.CharField(default='Pratica iniziale', max_length=100),
        ),
        migrations.AddField(
            model_name='pratica',
            name='utente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pratiche_immobiliari', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_file', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documenti/')),
                ('caricato_il', models.DateTimeField(auto_now_add=True)),
                ('pratica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='real_estate.pratica')),
            ],
        ),
        migrations.DeleteModel(
            name='ProfiloUtente',
        ),
    ]
