# Generated by Django 5.0.2 on 2025-05-20 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_remove_pratica_data_modifica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='nome_file',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='documento',
            name='file',
            field=models.FileField(upload_to='documenti_pratiche/'),
        ),
        migrations.CreateModel(
            name='PraticaImmobiliare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_azienda', models.CharField(max_length=255)),
                ('prodotto', models.CharField(max_length=255)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='documento',
            name='pratica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='real_estate.praticaimmobiliare'),
        ),
        migrations.DeleteModel(
            name='Pratica',
        ),
    ]
