# Generated by Django 5.0.2 on 2025-05-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_rename_nome_file_documento_nome_alter_documento_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-caricato_il'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documenti'},
        ),
        migrations.AlterModelOptions(
            name='praticaimmobiliare',
            options={'ordering': ['-data_creazione'], 'verbose_name': 'Pratica Immobiliare', 'verbose_name_plural': 'Pratiche Immobiliari'},
        ),
        migrations.RemoveField(
            model_name='praticaimmobiliare',
            name='prodotto',
        ),
        migrations.AddField(
            model_name='praticaimmobiliare',
            name='tipo_personalizzato',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Altro tipo (se specificato)'),
        ),
        migrations.AddField(
            model_name='praticaimmobiliare',
            name='tipo_pratica',
            field=models.CharField(choices=[('preliminare', 'Preliminare di vendita'), ('rogito', 'Rogito notarile'), ('visura', 'Visura ipotecaria'), ('catastale', 'Certificato catastale'), ('altro', 'Altro (specificare)')], default='preliminare', max_length=50, verbose_name='Tipo di pratica'),
            preserve_default=False,
        ),
    ]
