# Generated by Django 5.0.2 on 2025-05-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_alter_documento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticaimmobiliare',
            name='completata',
            field=models.BooleanField(default=False),
        ),
    ]
