# Generated by Django 5.0.2 on 2025-05-22 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_profiloutente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='praticaimmobiliare',
            name='notaio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pratiche_notaio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documenti_pratiche/'),
        ),
        migrations.AlterField(
            model_name='praticaimmobiliare',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratiche_utente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profiloutente',
            name='ruolo',
            field=models.CharField(choices=[('admin', 'Amministratore'), ('store_manager', 'Store Manager'), ('agente', 'Agente'), ('notaio', 'Notaio')], max_length=20),
        ),
    ]
