# Generated by Django 5.0.2 on 2025-05-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0007_praticaimmobiliare_notaio_alter_documento_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticaimmobiliare',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note interne / comunicazioni'),
        ),
    ]
