# Generated by Django 5.0.2 on 2025-05-22 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0008_praticaimmobiliare_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaPratica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pratica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_pratica', to='real_estate.praticaimmobiliare')),
                ('risposta_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risposte', to='real_estate.notapratica')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Note',
                'ordering': ['data_creazione'],
            },
        ),
    ]
