# Generated by Django 5.0.2 on 2025-05-22 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0009_notapratica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAttivitaPratica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azione', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pratica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_attivita', to='real_estate.praticaimmobiliare')),
                ('utente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log attività',
                'verbose_name_plural': 'Log attività',
                'ordering': ['-timestamp'],
            },
        ),
    ]
