# Generated by Django 5.0.2 on 2025-05-22 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0010_logattivitapratica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='praticaimmobiliare',
            name='geometra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pratiche_geometra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profiloutente',
            name='titolare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storemanager_titolare', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profiloutente',
            name='filiale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profiloutente',
            name='ruolo',
            field=models.CharField(choices=[('admin', 'Amministratore'), ('titolare_agenzia', 'Titolare Agenzia'), ('store_manager', 'Store Manager'), ('agente', 'Agente'), ('notaio', 'Notaio'), ('geometra', 'Geometra')], max_length=20),
        ),
    ]
