# Generated by Django 5.0.2 on 2025-05-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0011_praticaimmobiliare_geometra_profiloutente_titolare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticaimmobiliare',
            name='firma_digitale',
            field=models.BooleanField(default=False),
        ),
    ]
