# Generated by Django 5.0.2 on 2025-05-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0012_praticaimmobiliare_firma_digitale'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticaimmobiliare',
            name='data_scadenza',
            field=models.DateField(blank=True, null=True, verbose_name='Data di scadenza'),
        ),
    ]
