# Generated by Django 5.0.2 on 2025-05-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0013_praticaimmobiliare_data_scadenza'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiloutente',
            name='in_fase_di_registrazione',
            field=models.BooleanField(default=True),
        ),
    ]
