# Generated by Django 5.0.2 on 2025-05-22 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0014_profiloutente_in_fase_di_registrazione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profiloutente',
            name='store_manager',
            field=models.ForeignKey(blank=True, help_text='Solo per agenti: store manager di riferimento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_manager_utenti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profiloutente',
            name='titolare',
            field=models.ForeignKey(blank=True, help_text='Solo per store manager e agenti: titolare del gruppo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titolare_utenti', to=settings.AUTH_USER_MODEL),
        ),
    ]
