# Generated by Django 5.0.2 on 2025-05-26 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0015_profiloutente_store_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnuncioAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('tipologia', models.CharField(choices=[('foto', 'Carica Foto'), ('video', 'Carica Video')], max_length=10)),
                ('immagini', models.FileField(blank=True, null=True, upload_to='annunci/immagini/')),
                ('video', models.FileField(blank=True, null=True, upload_to='annunci/video/')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('elaborato', models.BooleanField(default=False)),
                ('video_generato', models.FileField(blank=True, null=True, upload_to='annunci/finali/')),
                ('testo_generato', models.TextField(blank=True)),
                ('pratica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annunci_ai', to='real_estate.praticaimmobiliare')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annuncio AI',
                'verbose_name_plural': 'Annunci AI',
            },
        ),
    ]
