# Generated by Django 5.0.2 on 2025-05-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0016_annuncioai'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiloutente',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='loghi_utente/'),
        ),
        migrations.AddField(
            model_name='profiloutente',
            name='sito_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
