# Generated by Django 5.0.2 on 2025-05-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0017_profiloutente_logo_profiloutente_sito_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticaimmobiliare',
            name='acquirente_cellulare',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='praticaimmobiliare',
            name='acquirente_cognome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='praticaimmobiliare',
            name='acquirente_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='praticaimmobiliare',
            name='acquirente_nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='praticaimmobiliare',
            name='venditore_cellulare',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='praticaimmobiliare',
            name='venditore_cognome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='praticaimmobiliare',
            name='venditore_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='praticaimmobiliare',
            name='venditore_indirizzo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='praticaimmobiliare',
            name='venditore_nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='praticaimmobiliare',
            name='tipo_pratica',
            field=models.CharField(choices=[('preliminare', 'Preliminare'), ('rogito', 'Rogito'), ('visura', 'Visura'), ('catastale', 'Catastale'), ('altro', 'Altro')], max_length=50, verbose_name='Tipo di pratica'),
        ),
        migrations.AlterField(
            model_name='profiloutente',
            name='ruolo',
            field=models.CharField(choices=[('admin', 'Admin'), ('titolare_agenzia', 'Titolare Agenzia'), ('store_manager', 'Store Manager'), ('agente', 'Agente'), ('notaio', 'Notaio'), ('geometra', 'Geometra')], max_length=20),
        ),
    ]
