# Generated by Django 5.0.2 on 2025-06-03 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0018_praticaimmobiliare_acquirente_cellulare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praticaimmobiliare',
            name='geometra',
            field=models.ForeignKey(blank=True, limit_choices_to={'in_fase_di_registrazione': False, 'ruolo': 'geometra'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pratiche_geometra', to='real_estate.profiloutente'),
        ),
        migrations.AlterField(
            model_name='praticaimmobiliare',
            name='notaio',
            field=models.ForeignKey(blank=True, limit_choices_to={'in_fase_di_registrazione': False, 'ruolo': 'notaio'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pratiche_notaio', to='real_estate.profiloutente'),
        ),
    ]
