# Generated by Django 5.0.2 on 2025-05-20 14:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pratica',
            name='nome_azienda',
        ),
        migrations.RemoveField(
            model_name='pratica',
            name='prodotto',
        ),
        migrations.AddField(
            model_name='pratica',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pratica',
            name='nome_pratica',
            field=models.CharField(default='Nuova pratica', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pratica',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratiche_fiscali', to=settings.AUTH_USER_MODEL),
        ),
    ]
